Update luogu.ts
piterator-org/luogu-discussion-archive pull request #21
Opened 2024-06-10 11:54 UTC by LuohanXiao

[#19](https://github.com/piterator-org/luogu-discussion-archive/issues/19)

[#20 ](https://github.com/piterator-org/luogu-discussion-archive/issues/20)

2024-06-11 01:25 UTC, wxh06 requested changes
请确保自己知道自己在修改什么，不要仅仅简单地进行全文替换来水 PR。

2024-06-11 01:25 UTC, wxh06 commented on packages/viewer/src/lib/luogu.ts
> +export const judgementUrl = "https://www.luogu.com/judgement";
`https://www.luogu.com/judgement` 能正常访问吗？

2024-06-11 01:25 UTC, wxh06 commented on packages/viewer/src/lib/luogu.ts
> +  url.hostname === "www.luogu.com" && isHTTPorHTTPS(url);
这个函数的作用是判断 URL 是否为洛谷内链，这么修改是否不妥？

2024-06-11 14:35 UTC, bohanjun requested changes
The changes you made is just simply replace all legacy luogu domains into new domains in our viewer. It's not hard to guess why you haven't also changed these domains in our archive module. The only possible reason I guess is that you are completely unfamiliar to our project. Thus I suggest you carefully read throughout our codes, and then you may pr again.

2024-06-18 06:32 UTC, wxh06 commented
Fixed in #22.

2024-06-18 06:32 UTC, closed without merging